### ISSUE TITLE
Eliminate Framework Dependencies

### ISSUE THREAD

**Issue by aganders3** [gpilab/conda-distro#4]
I'd like to reduce the dependencies for GPI so solving the conda "environment" gets easier. Here's the list of things I think you need to actually run GPI itself. Of course when you install any nodes, this is insufficient and you will likely need `scipy`, `matplotlib`, etc.

This gets a bit gray when thinking about `eigen` and `fftw` in particular since the framework contains (in PyFI) the wrapped functions, so I'm inclined to leave them in.

With this structure, we can still add dependencies when installing the `gpi-core-nodes` via `conda`, but it will make installing the core nodes by cloning the git repo a bit fuzzier since a user would need to manually install some additional packages (and it may not be clear which until they fail at runtime).

Any thoughts?

The `meta.yaml` for the framework would then look like this. If you want to play with this I have builds uploaded (for mac) to my conda channel (`conda install gpi -c aganders3`).
```
requirements:
  run:
    - eigen
    - fftw
    - numpy >=1.11,<2
    - psutil
    - pyopengl
    - python
    - pyqt {{ pyqt }}
    - qt {{ qt }}
    - sip
    - qimage2ndarray
  build:
    - python
```
